#!/bin/bash

#//todo Skip if --provision is used

# Parse through each file in the directory and use the file name to import the SQL file into the database of the same name
cd /srv/database/backups/
sql_count=`ls -1 *.sql 2>/dev/null | wc -l`

if [ $sql_count != 0 ]
then
	printf "Importing new database backups. Run provision to also overwrite the existing.\n"

	for file in $( ls *.sql )
	do
		pre_dot=${file%%.sql}
		mysql_cmd='SHOW TABLES FROM `'$pre_dot'`' # Required to support hypens in database names
		db_exist=`mysql -u root -proot --skip-column-names -e "$mysql_cmd"`

		# If the table doesn't exist yet...
		if [ "$db_exist" == "" ]
		then

			# Create DB
			printf " * Creating $pre_dot database with admin/admin credentials.\n"
			mysql -u root -proot -e "CREATE DATABASE $pre_dot"
			mysql -u root -proot -e "GRANT ALL PRIVILEGES ON $pre_dot.* TO admin@localhost IDENTIFIED BY 'admin'"

			# Import .sql
			printf "   Importing $file\n"
			mysql -u root -proot $pre_dot < $pre_dot.sql

		fi

	done
fi
